services:
  todo_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo_api
#    image: betodroid/todo_backend_api:latest
    container_name: todo_api
    command: >
      bash -c "python manage.py migrate
      && python manage.py populate_db_static_data
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - todo_db
    env_file:
      - .env

  todo_db:
    image: postgres:17.0
    container_name: todo_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: