#global:
#  scrape_interval: 20s
#  evaluation_interval: 20s
#
#scrape_configs:
#  - job_name: "todo_monitoring"
#    metrics_path: /metrics
#    static_configs:
#      - targets: [ "0.0.0.0:8000" ]
#

global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'todo_app'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']