# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'todo_api-stuff'
    metrics_path: '/prometheus/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']  # NOTE 2 HOURS OF MY LIFE https://stackoverflow.com/questions/54397463/getting-error-get-http-localhost9443-metrics-dial-tcp-127-0-0-19443-conne
        labels:
          alias: "todo_api"