# Generated by Django 5.1.6 on 2025-02-25 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tasks_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_duration', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Started', 'Started'), ('Created', 'Created')], default='Created', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
